AWSTemplateFormatVersion: 2010-09-09
Description: Cafe application

Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"

  CafeNetworkParameter:
    Type: String
    Default: update-cafe-network

  InstanceTypeParameter:
    Type: String
    Description: Enter t2.small, t2.medium, t3.small or t3.medium. Default is t2.small.
    Default: t2.small
    AllowedValues:
      - t2.small
      - t2.medium
      - t3.small
      - t3.medium

Mappings:
  RegionMap:
    ap-southeast-1:
      "keypair": "dolphin"
    ap-northeast-1:
      "keypair": "pigeon"

Resources:
  CafeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CafeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ssmParam
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "ssm:*"
                Resource: "arn:aws:ssm:*:*:parameter/*"
  CafeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref CafeRole
  CafeSG: #logical ID Cafe Security Group
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH, HTTP access
      VpcId: !ImportValue
        "Fn::Sub": "${CafeNetworkParameter}-VpcID"
      Tags:
        - Key: Name
          Value: CafeSG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
  CafeInstance: #logical ID
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !FindInMap [RegionMap, !Ref "AWS::Region", keypair]
      IamInstanceProfile: !Ref CafeInstanceProfile
      NetworkInterfaces:
        - DeviceIndex: "0"
          AssociatePublicIpAddress: "true"
          SubnetId: !ImportValue
            "Fn::Sub": "${CafeNetworkParameter}-SubnetID"
          GroupSet:
            - !Ref CafeSG
      Tags:
        - Key: Name
          Value: Cafe Web Server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum -y update
          yum install -y httpd mariadb-server wget
          amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
          systemctl enable httpd
          systemctl start httpd
          systemctl enable mariadb
          systemctl start mariadb
          wget https://aws-tc-largeobjects.s3-us-west-2.amazonaws.com/ILT-TF-200-ACACAD-20-EN/mod10-challenge/cafe-app.sh
          chmod +x cafe-app.sh
          ./cafe-app.sh

Outputs:
  WebServerPublicIP:
    Value: !GetAtt "CafeInstance.PublicIp"
