name: Deploy CloudFormation

on:
  push:
    branches:
      - main # runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 # change to your region

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file main.yaml \
            --capabilities CAPABILITY_NAMED_IAM
